name:                web-haskell
version:             0.1.0.0
github:              ""
license:             BSD3
author:              "Nhan Thai "
maintainer:          "Nhan Thai"
copyright:           "2020 Nhan Thai"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/scoville/graphql>

default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - GADTs
  - Arrows
  - OverloadedStrings
  - FlexibleContexts
  - FlexibleInstances
  - TypeFamilies
  - TypeApplications
  - StandaloneDeriving
  - TypeSynonymInstances
  - MultiParamTypeClasses
  - GeneralizedNewtypeDeriving
  - TemplateHaskell
  - QuasiQuotes
  - ScopedTypeVariables
  - DuplicateRecordFields
  - LambdaCase
  - NamedFieldPuns


dependencies:
  - base >= 4.7 && < 5
  - transformers
  - text
  - mtl
  - product-profunctors
  - postgresql-simple
  - postgresql-simple-url
  - resource-pool
  - time
  - monad-control
  - bytestring
  - scientific
  - exceptions
  - extra
  - aeson
  - opaleye
  - unordered-containers
  - morpheus-graphql
  - scotty
  - envy
  - load-env
  - stm
  - jwt
  - containers
  - transformers-base
  - bcrypt


library:
  source-dirs: src

executables:
  web-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wmissing-signatures
    dependencies:
      - web-haskell

tests:
  graphql-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wmissing-signatures
    dependencies:
      - web-haskell
